# Generated by Django 3.2.12 on 2024-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20240111_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='price_updated',
            name='date',
            field=models.DateField(verbose_name='Price Updated Date'),
        ),
    ]
