# Generated by Django 3.2.12 on 2024-01-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20240111_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collections',
            field=models.ManyToManyField(to='main_app.Collection'),
        ),
    ]
